runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php
- url: /login\.php
  script: login.php
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.(php|css|js))$
  script: \1
  
- url: /css
  static_dir: css
  
- url: /img
  static_dir: img
  
- url: /js
  static_dir: js
  
- url: /sound
  static_dir: sound